import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Download, Eye, Filter, FileText, FileSpreadsheet, Users, Activity, Calendar, TrendingUp } from "lucide-react";

interface ReportData {
  id: string;
  title: string;
  type: 'patient' | 'staff' | 'appointment' | 'financial' | 'medical';
  generatedBy: string;
  createdAt: string;
  status: 'completed' | 'pending' | 'failed';
  format: 'pdf' | 'csv' | 'xlsx';
  description: string;
  recordCount: number;
}

interface ReportListProps {
  reports: ReportData[];
  onDownload: (reportId: string) => void;
  onView: (reportId: string) => void;
}

export const ReportList = ({ reports, onDownload, onView }: ReportListProps) => {
  const getStatusColor = (status: string) => {
    switch (status) {
      case "completed":
        return "bg-green-500/10 text-green-700 dark:text-green-400";
      case "pending":
        return "bg-yellow-500/10 text-yellow-700 dark:text-yellow-400";
      case "failed":
        return "bg-red-500/10 text-red-700 dark:text-red-400";
      default:
        return "bg-muted text-muted-foreground";
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case "patient":
        return <Users className="h-4 w-4" />;
      case "staff":
        return <Activity className="h-4 w-4" />;
      case "appointment":
        return <Calendar className="h-4 w-4" />;
      case "financial":
        return <TrendingUp className="h-4 w-4" />;
      case "medical":
        return <FileText className="h-4 w-4" />;
      default:
        return <FileText className="h-4 w-4" />;
    }
  };

  const getFormatIcon = (format: string) => {
    switch (format) {
      case "pdf":
        return <FileText className="h-4 w-4 text-red-500" />;
      case "csv":
        return <FileSpreadsheet className="h-4 w-4 text-green-500" />;
      case "xlsx":
        return <FileSpreadsheet className="h-4 w-4 text-blue-500" />;
      default:
        return <FileText className="h-4 w-4" />;
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex gap-4 items-center">
        <div className="flex-1">
          <Input placeholder="Search reports..." className="max-w-sm" />
        </div>
        <Button variant="outline" size="sm">
          <Filter className="h-4 w-4 mr-2" />
          Filter
        </Button>
      </div>

      <div className="grid gap-4">
        {reports.map((report) => (
          <Card key={report.id} className="hover:shadow-md transition-shadow">
            <CardContent className="p-6">
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-4 flex-1">
                  <div className="p-2 bg-primary/10 rounded-lg">
                    {getTypeIcon(report.type)}
                  </div>
                  <div className="flex-1 space-y-2">
                    <div className="flex items-center gap-2">
                      <h3 className="font-semibold text-foreground">{report.title}</h3>
                      <Badge className={getStatusColor(report.status)}>
                        {report.status}
                      </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground">{report.description}</p>
                    <div className="flex items-center gap-4 text-sm text-muted-foreground">
                      <span>Generated by {report.generatedBy}</span>
                      <span>•</span>
                      <span>{report.createdAt}</span>
                      <span>•</span>
                      <span>{report.recordCount} records</span>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {getFormatIcon(report.format)}
                  <Button 
                    variant="outline" 
                    size="sm" 
                    onClick={() => onDownload(report.id)}
                    disabled={report.status !== 'completed'}
                  >
                    <Download className="h-4 w-4 mr-2" />
                    Download
                  </Button>
                  <Button 
                    variant="ghost" 
                    size="sm"
                    onClick={() => onView(report.id)}
                  >
                    <Eye className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
};